version: '3.6'
services:
  shib-test-site:
    image: uscdev/shib-test-site
    ports:
      - 8001:80
    networks:
      proxy:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  proxy:
    external: true
