version: '3.1'
services:
  shib-test:
    image: uscdev/shib-test
    ports:
      - 8001:80
    networks:
      web-bus:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  web-bus:
    external:
      name: web-bus
